from PyQt5 import QtCore, QtWidgets, QtGui


class Ui_DynamicPointsDensitySignalWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(816, 725)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(420, 60, 271, 311))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.PointsDensityhorizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.PointsDensityhorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.PointsDensityhorizontalSlider.setObjectName("PointsDensityhorizontalSlider")
        self.gridLayout_10.addWidget(self.PointsDensityhorizontalSlider, 7, 0, 1, 1)
        self.VerticalOffsethorizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.VerticalOffsethorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.VerticalOffsethorizontalSlider.setObjectName("VerticalOffsethorizontalSlider")
        self.gridLayout_10.addWidget(self.VerticalOffsethorizontalSlider, 6, 0, 1, 1)
        self.AccelerationTimehorizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.AccelerationTimehorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.AccelerationTimehorizontalSlider.setObjectName("AccelerationTimehorizontalSlider")
        self.gridLayout_10.addWidget(self.AccelerationTimehorizontalSlider, 1, 0, 1, 1)
        self.StartTimehorizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.StartTimehorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.StartTimehorizontalSlider.setObjectName("StartTimehorizontalSlider")
        self.gridLayout_10.addWidget(self.StartTimehorizontalSlider, 0, 0, 1, 1)
        self.HighLevelFrequencyhorizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.HighLevelFrequencyhorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.HighLevelFrequencyhorizontalSlider.setObjectName("HighLevelFrequencyhorizontalSlider")
        self.gridLayout_10.addWidget(self.HighLevelFrequencyhorizontalSlider, 5, 0, 1, 1)
        self.PlateauTimehorizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.PlateauTimehorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.PlateauTimehorizontalSlider.setObjectName("PlateauTimehorizontalSlider")
        self.gridLayout_10.addWidget(self.PlateauTimehorizontalSlider, 2, 0, 1, 1)
        self.DecelerationTimehorizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.DecelerationTimehorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.DecelerationTimehorizontalSlider.setObjectName("DecelerationTimehorizontalSlider")
        self.gridLayout_10.addWidget(self.DecelerationTimehorizontalSlider, 3, 0, 1, 1)
        self.LowLevelFrequencyhorizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.LowLevelFrequencyhorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.LowLevelFrequencyhorizontalSlider.setObjectName("LowLevelFrequencyhorizontalSlider")
        self.gridLayout_10.addWidget(self.LowLevelFrequencyhorizontalSlider, 4, 0, 1, 1)
        self.EndTimehorizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.EndTimehorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.EndTimehorizontalSlider.setObjectName("EndTimehorizontalSlider")
        self.gridLayout_10.addWidget(self.EndTimehorizontalSlider, 8, 0, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(700, 60, 65, 311))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lineEditSliderTimeFromMax = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditSliderTimeFromMax.setReadOnly(True)
        self.lineEditSliderTimeFromMax.setObjectName("lineEditSliderTimeFromMax")
        self.gridLayout_8.addWidget(self.lineEditSliderTimeFromMax, 0, 0, 1, 1)
        self.lineEditSliderTimeToMax = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditSliderTimeToMax.setReadOnly(True)
        self.lineEditSliderTimeToMax.setObjectName("lineEditSliderTimeToMax")
        self.gridLayout_8.addWidget(self.lineEditSliderTimeToMax, 1, 0, 1, 1)
        self.lineEditSliderAmplitudeMax = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditSliderAmplitudeMax.setReadOnly(True)
        self.lineEditSliderAmplitudeMax.setObjectName("lineEditSliderAmplitudeMax")
        self.gridLayout_8.addWidget(self.lineEditSliderAmplitudeMax, 2, 0, 1, 1)
        self.lineEditSliderTimeFromMax_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditSliderTimeFromMax_2.setReadOnly(True)
        self.lineEditSliderTimeFromMax_2.setObjectName("lineEditSliderTimeFromMax_2")
        self.gridLayout_8.addWidget(self.lineEditSliderTimeFromMax_2, 3, 0, 1, 1)
        self.lineEditSliderTimeToMax_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditSliderTimeToMax_2.setReadOnly(True)
        self.lineEditSliderTimeToMax_2.setObjectName("lineEditSliderTimeToMax_2")
        self.gridLayout_8.addWidget(self.lineEditSliderTimeToMax_2, 4, 0, 1, 1)
        self.lineEditSliderAmplitudeMax_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditSliderAmplitudeMax_2.setReadOnly(True)
        self.lineEditSliderAmplitudeMax_2.setObjectName("lineEditSliderAmplitudeMax_2")
        self.gridLayout_8.addWidget(self.lineEditSliderAmplitudeMax_2, 5, 0, 1, 1)
        self.lineEditSliderTimeFromMax_3 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditSliderTimeFromMax_3.setReadOnly(True)
        self.lineEditSliderTimeFromMax_3.setObjectName("lineEditSliderTimeFromMax_3")
        self.gridLayout_8.addWidget(self.lineEditSliderTimeFromMax_3, 6, 0, 1, 1)
        self.lineEditSliderTimeToMax_3 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditSliderTimeToMax_3.setReadOnly(True)
        self.lineEditSliderTimeToMax_3.setObjectName("lineEditSliderTimeToMax_3")
        self.gridLayout_8.addWidget(self.lineEditSliderTimeToMax_3, 7, 0, 1, 1)
        self.lineEditSliderAmplitudeMax_3 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditSliderAmplitudeMax_3.setReadOnly(True)
        self.lineEditSliderAmplitudeMax_3.setObjectName("lineEditSliderAmplitudeMax_3")
        self.gridLayout_8.addWidget(self.lineEditSliderAmplitudeMax_3, 8, 0, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(340, 60, 65, 311))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lineEditSliderAmplitudeMin_2 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEditSliderAmplitudeMin_2.setReadOnly(True)
        self.lineEditSliderAmplitudeMin_2.setObjectName("lineEditSliderAmplitudeMin_2")
        self.gridLayout_9.addWidget(self.lineEditSliderAmplitudeMin_2, 5, 0, 1, 1)
        self.lineEditSliderAmplitudeMin = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEditSliderAmplitudeMin.setReadOnly(True)
        self.lineEditSliderAmplitudeMin.setObjectName("lineEditSliderAmplitudeMin")
        self.gridLayout_9.addWidget(self.lineEditSliderAmplitudeMin, 2, 0, 1, 1)
        self.lineEditSliderTimeToMin_2 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEditSliderTimeToMin_2.setReadOnly(True)
        self.lineEditSliderTimeToMin_2.setObjectName("lineEditSliderTimeToMin_2")
        self.gridLayout_9.addWidget(self.lineEditSliderTimeToMin_2, 4, 0, 1, 1)
        self.lineEditSliderTimeToMin_3 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEditSliderTimeToMin_3.setReadOnly(True)
        self.lineEditSliderTimeToMin_3.setObjectName("lineEditSliderTimeToMin_3")
        self.gridLayout_9.addWidget(self.lineEditSliderTimeToMin_3, 7, 0, 1, 1)
        self.lineEditSliderTimeFromMin_2 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEditSliderTimeFromMin_2.setReadOnly(True)
        self.lineEditSliderTimeFromMin_2.setObjectName("lineEditSliderTimeFromMin_2")
        self.gridLayout_9.addWidget(self.lineEditSliderTimeFromMin_2, 3, 0, 1, 1)
        self.lineEditSliderTimeFromMin = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEditSliderTimeFromMin.setReadOnly(True)
        self.lineEditSliderTimeFromMin.setObjectName("lineEditSliderTimeFromMin")
        self.gridLayout_9.addWidget(self.lineEditSliderTimeFromMin, 0, 0, 1, 1)
        self.lineEditSliderTimeToMin = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEditSliderTimeToMin.setReadOnly(True)
        self.lineEditSliderTimeToMin.setObjectName("lineEditSliderTimeToMin")
        self.gridLayout_9.addWidget(self.lineEditSliderTimeToMin, 1, 0, 1, 1)
        self.lineEditSliderTimeFromMin_3 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEditSliderTimeFromMin_3.setReadOnly(True)
        self.lineEditSliderTimeFromMin_3.setObjectName("lineEditSliderTimeFromMin_3")
        self.gridLayout_9.addWidget(self.lineEditSliderTimeFromMin_3, 6, 0, 1, 1)
        self.lineEditSliderAmplitudeMin_3 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEditSliderAmplitudeMin_3.setReadOnly(True)
        self.lineEditSliderAmplitudeMin_3.setObjectName("lineEditSliderAmplitudeMin_3")
        self.gridLayout_9.addWidget(self.lineEditSliderAmplitudeMin_3, 8, 0, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(200, 60, 65, 311))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.StartTimelineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.StartTimelineEdit.setObjectName("StartTimelineEdit")
        self.verticalLayout.addWidget(self.StartTimelineEdit)
        self.AccelerationTimelineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.AccelerationTimelineEdit.setObjectName("AccelerationTimelineEdit")
        self.verticalLayout.addWidget(self.AccelerationTimelineEdit)
        self.PlateauTimelineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.PlateauTimelineEdit.setObjectName("PlateauTimelineEdit")
        self.verticalLayout.addWidget(self.PlateauTimelineEdit)
        self.DecelerationTimelineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.DecelerationTimelineEdit.setObjectName("DecelerationTimelineEdit")
        self.verticalLayout.addWidget(self.DecelerationTimelineEdit)
        self.LowLevelFrequencylineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.LowLevelFrequencylineEdit.setObjectName("LowLevelFrequencylineEdit")
        self.verticalLayout.addWidget(self.LowLevelFrequencylineEdit)
        self.HighLevelFrequencylineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.HighLevelFrequencylineEdit.setObjectName("HighLevelFrequencylineEdit")
        self.verticalLayout.addWidget(self.HighLevelFrequencylineEdit)
        self.VerticalOffsetlineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.VerticalOffsetlineEdit.setObjectName("VerticalOffsetlineEdit")
        self.verticalLayout.addWidget(self.VerticalOffsetlineEdit)
        self.PointsDensitylineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.PointsDensitylineEdit.setObjectName("PointsDensitylineEdit")
        self.verticalLayout.addWidget(self.PointsDensitylineEdit)
        self.EndTimelineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.EndTimelineEdit.setObjectName("EndTimelineEdit")
        self.verticalLayout.addWidget(self.EndTimelineEdit)
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(61, 61, 131, 301))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelStartTime = QtWidgets.QLabel(self.layoutWidget4)
        self.labelStartTime.setObjectName("labelStartTime")
        self.verticalLayout_2.addWidget(self.labelStartTime)
        self.labelAccelerationTime = QtWidgets.QLabel(self.layoutWidget4)
        self.labelAccelerationTime.setObjectName("labelAccelerationTime")
        self.verticalLayout_2.addWidget(self.labelAccelerationTime)
        self.labelPlateauTime = QtWidgets.QLabel(self.layoutWidget4)
        self.labelPlateauTime.setObjectName("labelPlateauTime")
        self.verticalLayout_2.addWidget(self.labelPlateauTime)
        self.labelDecelerationTime = QtWidgets.QLabel(self.layoutWidget4)
        self.labelDecelerationTime.setObjectName("labelDecelerationTime")
        self.verticalLayout_2.addWidget(self.labelDecelerationTime)
        self.labeLowLevelFrequency = QtWidgets.QLabel(self.layoutWidget4)
        self.labeLowLevelFrequency.setObjectName("labeLowLevelFrequency")
        self.verticalLayout_2.addWidget(self.labeLowLevelFrequency)
        self.labelHighLevelFrequency = QtWidgets.QLabel(self.layoutWidget4)
        self.labelHighLevelFrequency.setObjectName("labelHighLevelFrequency")
        self.verticalLayout_2.addWidget(self.labelHighLevelFrequency)
        self.labelVerticalOffset = QtWidgets.QLabel(self.layoutWidget4)
        self.labelVerticalOffset.setObjectName("labelVerticalOffset")
        self.verticalLayout_2.addWidget(self.labelVerticalOffset)
        self.labelPointsDensity = QtWidgets.QLabel(self.layoutWidget4)
        self.labelPointsDensity.setObjectName("labelPointsDensity")
        self.verticalLayout_2.addWidget(self.labelPointsDensity)
        self.labelEndTime = QtWidgets.QLabel(self.layoutWidget4)
        self.labelEndTime.setObjectName("labelEndTime")
        self.verticalLayout_2.addWidget(self.labelEndTime)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 390, 621, 321))
        self.label.setMinimumSize(QtCore.QSize(621, 0))
        self.label.setMaximumSize(QtCore.QSize(621, 321))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(
            "C:\\Users\\79137\\Pasha\\6 semester\\Coursework\\GUI_test_code\\../../../7 semester/Диплом/Illustration.png"))
        self.label.setObjectName("label")
        self.ConfigFileNamelineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.ConfigFileNamelineEdit.setGeometry(QtCore.QRect(200, 20, 221, 22))
        self.ConfigFileNamelineEdit.setObjectName("ConfigFileNamelineEdit")
        self.ConfigFilenamelabel = QtWidgets.QLabel(self.centralwidget)
        self.ConfigFilenamelabel.setGeometry(QtCore.QRect(60, 20, 111, 16))
        self.ConfigFilenamelabel.setLineWidth(4)
        self.ConfigFilenamelabel.setObjectName("ConfigFilenamelabel")
        self.AutoFillpushButton = QtWidgets.QPushButton(self.centralwidget)
        self.AutoFillpushButton.setGeometry(QtCore.QRect(430, 20, 93, 28))
        self.AutoFillpushButton.setObjectName("AutoFillpushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 816, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEditSliderTimeFromMax.setText(_translate("MainWindow", "600"))
        self.lineEditSliderTimeToMax.setText(_translate("MainWindow", "600"))
        self.lineEditSliderAmplitudeMax.setText(_translate("MainWindow", "600"))
        self.lineEditSliderTimeFromMax_2.setText(_translate("MainWindow", "600"))
        self.lineEditSliderTimeToMax_2.setText(_translate("MainWindow", "600"))
        self.lineEditSliderAmplitudeMax_2.setText(_translate("MainWindow", "600"))
        self.lineEditSliderTimeFromMax_3.setText(_translate("MainWindow", "600"))
        self.lineEditSliderTimeToMax_3.setText(_translate("MainWindow", "600"))
        self.lineEditSliderAmplitudeMax_3.setText(_translate("MainWindow", "600"))
        self.lineEditSliderAmplitudeMin_2.setText(_translate("MainWindow", "0.0"))
        self.lineEditSliderAmplitudeMin.setText(_translate("MainWindow", "0.0"))
        self.lineEditSliderTimeToMin_2.setText(_translate("MainWindow", "0.0"))
        self.lineEditSliderTimeToMin_3.setText(_translate("MainWindow", "0.0"))
        self.lineEditSliderTimeFromMin_2.setText(_translate("MainWindow", "0.0"))
        self.lineEditSliderTimeFromMin.setText(_translate("MainWindow", "0.0"))
        self.lineEditSliderTimeToMin.setText(_translate("MainWindow", "0.0"))
        self.lineEditSliderTimeFromMin_3.setText(_translate("MainWindow", "0.0"))
        self.lineEditSliderAmplitudeMin_3.setText(_translate("MainWindow", "0.0"))
        self.labelStartTime.setText(_translate("MainWindow", "Start Time:"))
        self.labelAccelerationTime.setText(_translate("MainWindow", "Acceleration Time:"))
        self.labelPlateauTime.setText(_translate("MainWindow", "Plateau Time:"))
        self.labelDecelerationTime.setText(_translate("MainWindow", "Deceleration Time:"))
        self.labeLowLevelFrequency.setText(_translate("MainWindow", "Low-level Frequency:"))
        self.labelHighLevelFrequency.setText(_translate("MainWindow", "High-level Frequency:"))
        self.labelVerticalOffset.setText(_translate("MainWindow", "Vertical Offset:"))
        self.labelPointsDensity.setText(_translate("MainWindow", "Points Density"))
        self.labelEndTime.setText(_translate("MainWindow", "End Time:"))
        self.ConfigFilenamelabel.setText(_translate("MainWindow", "Config Filename"))
        self.AutoFillpushButton.setText(_translate("MainWindow", "Auto-Fill"))




