from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(842, 490)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.aaa = QtWidgets.QTabWidget(self.centralwidget)
        self.aaa.setObjectName("aaa")
        self.ConnectionParametersTab = QtWidgets.QWidget()
        self.ConnectionParametersTab.setObjectName("ConnectionParametersTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ConnectionParametersTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.ConnectionParametersTab)
        self.frame.setMinimumSize(QtCore.QSize(718, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter_2 = QtWidgets.QSplitter(self.frame)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.label = QtWidgets.QLabel(self.splitter_2)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.splitter_2)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.splitter_2)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.splitter_2)
        self.label_6.setObjectName("label_6")
        self.ComPortNumberlabel = QtWidgets.QLabel(self.splitter_2)
        self.ComPortNumberlabel.setObjectName("ComPortNumberlabel")
        self.BaudRateLabel = QtWidgets.QLabel(self.splitter_2)
        self.BaudRateLabel.setObjectName("BaudRateLabel")
        self.gridLayout_2.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.frame)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.ProtocolcomboBox = QtWidgets.QComboBox(self.splitter)
        self.ProtocolcomboBox.setObjectName("ProtocolcomboBox")
        self.ProtocolcomboBox.addItem("")
        self.ProtocolcomboBox.setItemText(0, "")
        self.ProtocolcomboBox.addItem("")
        self.ProtocolcomboBox.addItem("")
        self.ByteSizecomboBox = QtWidgets.QComboBox(self.splitter)
        self.ByteSizecomboBox.setObjectName("ByteSizecomboBox")
        self.ByteSizecomboBox.addItem("")
        self.ByteSizecomboBox.setItemText(0, "")
        self.ByteSizecomboBox.addItem("")
        self.ByteSizecomboBox.addItem("")
        self.ParitycomboBox = QtWidgets.QComboBox(self.splitter)
        self.ParitycomboBox.setObjectName("ParitycomboBox")
        self.ParitycomboBox.addItem("")
        self.ParitycomboBox.setItemText(0, "")
        self.ParitycomboBox.addItem("")
        self.ParitycomboBox.addItem("")
        self.ParitycomboBox.addItem("")
        self.StopBitscomboBox = QtWidgets.QComboBox(self.splitter)
        self.StopBitscomboBox.setObjectName("StopBitscomboBox")
        self.StopBitscomboBox.addItem("")
        self.StopBitscomboBox.setItemText(0, "")
        self.StopBitscomboBox.addItem("")
        self.StopBitscomboBox.addItem("")
        self.COMPortcomboBox = QtWidgets.QComboBox(self.splitter)
        self.COMPortcomboBox.setObjectName("COMPortcomboBox")
        self.COMPortcomboBox.addItem("")
        self.COMPortcomboBox.setItemText(0, "")
        self.COMPortcomboBox.addItem("")
        self.COMPortcomboBox.addItem("")
        self.COMPortcomboBox.addItem("")
        self.COMPortcomboBox.addItem("")
        self.COMPortcomboBox.addItem("")
        self.COMPortcomboBox.addItem("")
        self.COMPortcomboBox.addItem("")
        self.BaudRatecomboBox = QtWidgets.QComboBox(self.splitter)
        self.BaudRatecomboBox.setObjectName("BaudRatecomboBox")
        self.BaudRatecomboBox.addItem("")
        self.BaudRatecomboBox.setItemText(0, "")
        self.BaudRatecomboBox.addItem("")
        self.BaudRatecomboBox.addItem("")
        self.BaudRatecomboBox.addItem("")
        self.BaudRatecomboBox.addItem("")
        self.gridLayout_2.addWidget(self.splitter, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_2.addWidget(self.frame)
        self.splitter_3 = QtWidgets.QSplitter(self.ConnectionParametersTab)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.AutoConnectpushButton = QtWidgets.QPushButton(self.splitter_3)
        self.AutoConnectpushButton.setObjectName("AutoConnectpushButton")
        self.ConnectpushButton = QtWidgets.QPushButton(self.splitter_3)
        self.ConnectpushButton.setObjectName("ConnectpushButton")
        self.verticalLayout_2.addWidget(self.splitter_3)
        self.aaa.addTab(self.ConnectionParametersTab, "")
        self.OutputFrequencySettingTab = QtWidgets.QWidget()
        self.OutputFrequencySettingTab.setObjectName("OutputFrequencySettingTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.OutputFrequencySettingTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_4 = QtWidgets.QFrame(self.OutputFrequencySettingTab)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.OutputFrequencylineEdit = QtWidgets.QLineEdit(self.frame_4)
        self.OutputFrequencylineEdit.setObjectName("OutputFrequencylineEdit")
        self.horizontalLayout_3.addWidget(self.OutputFrequencylineEdit)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.gridLayout_4.addWidget(self.frame_4, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.OutputFrequencySettingTab)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.FrequencyMinlineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.FrequencyMinlineEdit.setObjectName("FrequencyMinlineEdit")
        self.horizontalLayout.addWidget(self.FrequencyMinlineEdit)
        self.FrequencySetSlider = QtWidgets.QSlider(self.frame_2)
        self.FrequencySetSlider.setMaximum(50)
        self.FrequencySetSlider.setOrientation(QtCore.Qt.Horizontal)
        self.FrequencySetSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.FrequencySetSlider.setObjectName("FrequencySetSlider")
        self.horizontalLayout.addWidget(self.FrequencySetSlider)
        self.FrequencyMaxlineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.FrequencyMaxlineEdit.setObjectName("FrequencyMaxlineEdit")
        self.horizontalLayout.addWidget(self.FrequencyMaxlineEdit)
        self.gridLayout_4.addWidget(self.frame_2, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.OutputFrequencySettingTab)
        self.frame_3.setMinimumSize(QtCore.QSize(365, 0))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.SetFrequencypushButton = QtWidgets.QPushButton(self.frame_3)
        self.SetFrequencypushButton.setObjectName("SetFrequencypushButton")
        self.verticalLayout_4.addWidget(self.SetFrequencypushButton)
        self.StartFrequencypushButton = QtWidgets.QPushButton(self.frame_3)
        self.StartFrequencypushButton.setObjectName("StartFrequencypushButton")
        self.verticalLayout_4.addWidget(self.StartFrequencypushButton)
        self.StopFrequencypushButton = QtWidgets.QPushButton(self.frame_3)
        self.StopFrequencypushButton.setObjectName("StopFrequencypushButton")
        self.verticalLayout_4.addWidget(self.StopFrequencypushButton)
        self.gridLayout_4.addWidget(self.frame_3, 1, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.OutputFrequencySettingTab)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.RequestSetFrequencypushButton = QtWidgets.QPushButton(self.frame_5)
        self.RequestSetFrequencypushButton.setObjectName("RequestSetFrequencypushButton")
        self.verticalLayout_3.addWidget(self.RequestSetFrequencypushButton)
        self.RequestCurrentFrequencypushButton = QtWidgets.QPushButton(self.frame_5)
        self.RequestCurrentFrequencypushButton.setObjectName("RequestCurrentFrequencypushButton")
        self.verticalLayout_3.addWidget(self.RequestCurrentFrequencypushButton)
        self.gridLayout_4.addWidget(self.frame_5, 1, 1, 1, 1)
        self.aaa.addTab(self.OutputFrequencySettingTab, "")
        self.FrequencySignalSetting = QtWidgets.QWidget()
        self.FrequencySignalSetting.setObjectName("FrequencySignalSetting")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.FrequencySignalSetting)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.frame_7 = QtWidgets.QFrame(self.FrequencySignalSetting)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame_7)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.SignalTypecomboBox = QtWidgets.QComboBox(self.frame_7)
        self.SignalTypecomboBox.setObjectName("SignalTypecomboBox")
        self.SignalTypecomboBox.addItem("")
        self.SignalTypecomboBox.setItemText(0, "")
        self.SignalTypecomboBox.addItem("")
        self.SignalTypecomboBox.addItem("")
        self.SignalTypecomboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.SignalTypecomboBox)
        self.gridLayout.addWidget(self.frame_7, 0, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.FrequencySignalSetting)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout.addWidget(self.frame_6, 0, 1, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.FrequencySignalSetting)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.AccelerationTimelabel_2 = QtWidgets.QLabel(self.frame_9)
        self.AccelerationTimelabel_2.setObjectName("AccelerationTimelabel_2")
        self.horizontalLayout_5.addWidget(self.AccelerationTimelabel_2)
        self.AccDec1radioButton = QtWidgets.QRadioButton(self.frame_9)
        self.AccDec1radioButton.setChecked(True)
        self.AccDec1radioButton.setObjectName("AccDec1radioButton")
        self.horizontalLayout_5.addWidget(self.AccDec1radioButton)
        self.AccDec2radioButton = QtWidgets.QRadioButton(self.frame_9)
        self.AccDec2radioButton.setObjectName("AccDec2radioButton")
        self.horizontalLayout_5.addWidget(self.AccDec2radioButton)
        self.AccDec3radioButton = QtWidgets.QRadioButton(self.frame_9)
        self.AccDec3radioButton.setObjectName("AccDec3radioButton")
        self.horizontalLayout_5.addWidget(self.AccDec3radioButton)
        self.AccDec4radioButton = QtWidgets.QRadioButton(self.frame_9)
        self.AccDec4radioButton.setObjectName("AccDec4radioButton")
        self.horizontalLayout_5.addWidget(self.AccDec4radioButton)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        self.gridLayout.addWidget(self.frame_9, 1, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.FrequencySignalSetting)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout.addWidget(self.frame_8, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.aaa.addTab(self.FrequencySignalSetting, "")
        self.SignalSendingTab = QtWidgets.QWidget()
        self.SignalSendingTab.setObjectName("SignalSendingTab")
        self.pushButtonStartSignalSending = QtWidgets.QPushButton(self.SignalSendingTab)
        self.pushButtonStartSignalSending.setGeometry(QtCore.QRect(40, 60, 131, 41))
        self.pushButtonStartSignalSending.setObjectName("pushButtonStartSignalSending")
        self.PauseSendingradioButton = QtWidgets.QRadioButton(self.SignalSendingTab)
        self.PauseSendingradioButton.setGeometry(QtCore.QRect(40, 130, 95, 20))
        self.PauseSendingradioButton.setObjectName("PauseSendingradioButton")
        self.ResumeSendingradioButton = QtWidgets.QRadioButton(self.SignalSendingTab)
        self.ResumeSendingradioButton.setGeometry(QtCore.QRect(130, 130, 95, 20))
        self.ResumeSendingradioButton.setChecked(True)
        self.ResumeSendingradioButton.setAutoExclusive(True)
        self.ResumeSendingradioButton.setObjectName("ResumeSendingradioButton")
        self.pushButtonStopSignalSending = QtWidgets.QPushButton(self.SignalSendingTab)
        self.pushButtonStopSignalSending.setGeometry(QtCore.QRect(40, 170, 131, 41))
        self.pushButtonStopSignalSending.setObjectName("pushButtonStopSignalSending")
        self.EndlessSendingcheckBox = QtWidgets.QCheckBox(self.SignalSendingTab)
        self.EndlessSendingcheckBox.setGeometry(QtCore.QRect(200, 70, 191, 20))
        self.EndlessSendingcheckBox.setObjectName("EndlessSendingcheckBox")
        self.aaa.addTab(self.SignalSendingTab, "")
        self.gridLayout_3.addWidget(self.aaa, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 842, 26))
        self.menubar.setObjectName("menubar")
        self.menuConnection_Parameters = QtWidgets.QMenu(self.menubar)
        self.menuConnection_Parameters.setObjectName("menuConnection_Parameters")
        self.menuOutput_Frequency_Settings = QtWidgets.QMenu(self.menubar)
        self.menuOutput_Frequency_Settings.setObjectName("menuOutput_Frequency_Settings")
        self.menuNew = QtWidgets.QMenu(self.menubar)
        self.menuNew.setObjectName("menuNew")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuConnection_Parameters.addSeparator()
        self.menubar.addAction(self.menuConnection_Parameters.menuAction())
        self.menubar.addAction(self.menuOutput_Frequency_Settings.menuAction())
        self.menubar.addAction(self.menuNew.menuAction())

        self.retranslateUi(MainWindow)
        self.aaa.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Protocol:"))
        self.label_2.setText(_translate("MainWindow", "Byte size"))
        self.label_5.setText(_translate("MainWindow", "Parity:"))
        self.label_6.setText(_translate("MainWindow", "Stop Bits:"))
        self.ComPortNumberlabel.setText(_translate("MainWindow", "COM Port Number:"))
        self.BaudRateLabel.setText(_translate("MainWindow", "Baud Rate: "))
        self.ProtocolcomboBox.setItemText(1, _translate("MainWindow", "rtu"))
        self.ProtocolcomboBox.setItemText(2, _translate("MainWindow", "ascii"))
        self.ByteSizecomboBox.setItemText(1, _translate("MainWindow", "7"))
        self.ByteSizecomboBox.setItemText(2, _translate("MainWindow", "8"))
        self.ParitycomboBox.setItemText(1, _translate("MainWindow", "O"))
        self.ParitycomboBox.setItemText(2, _translate("MainWindow", "N"))
        self.ParitycomboBox.setItemText(3, _translate("MainWindow", "E"))
        self.StopBitscomboBox.setItemText(1, _translate("MainWindow", "1"))
        self.StopBitscomboBox.setItemText(2, _translate("MainWindow", "2"))
        self.COMPortcomboBox.setItemText(1, _translate("MainWindow", "COM1"))
        self.COMPortcomboBox.setItemText(2, _translate("MainWindow", "COM2"))
        self.COMPortcomboBox.setItemText(3, _translate("MainWindow", "COM3"))
        self.COMPortcomboBox.setItemText(4, _translate("MainWindow", "COM4"))
        self.COMPortcomboBox.setItemText(5, _translate("MainWindow", "COM5"))
        self.COMPortcomboBox.setItemText(6, _translate("MainWindow", "COM6"))
        self.COMPortcomboBox.setItemText(7, _translate("MainWindow", "COM7"))
        self.BaudRatecomboBox.setItemText(1, _translate("MainWindow", "1200"))
        self.BaudRatecomboBox.setItemText(2, _translate("MainWindow", "2400"))
        self.BaudRatecomboBox.setItemText(3, _translate("MainWindow", "3600"))
        self.BaudRatecomboBox.setItemText(4, _translate("MainWindow", "9600"))
        self.AutoConnectpushButton.setText(_translate("MainWindow", "Auto-Connect"))
        self.ConnectpushButton.setText(_translate("MainWindow", "Connect"))
        self.aaa.setTabText(self.aaa.indexOf(self.ConnectionParametersTab),
                            _translate("MainWindow", "Connection Parameters"))
        self.label_3.setText(_translate("MainWindow", "Output frequency:"))
        self.OutputFrequencylineEdit.setText(_translate("MainWindow", "0"))
        self.lineEdit.setText(_translate("MainWindow", "Hz"))
        self.FrequencyMinlineEdit.setText(_translate("MainWindow", "0"))
        self.FrequencyMaxlineEdit.setText(_translate("MainWindow", "100"))
        self.SetFrequencypushButton.setText(_translate("MainWindow", "Set frequency"))
        self.StartFrequencypushButton.setText(_translate("MainWindow", "Start"))
        self.StopFrequencypushButton.setText(_translate("MainWindow", "Stop"))
        self.RequestSetFrequencypushButton.setText(_translate("MainWindow", "Request Set \n"
                                                                            "Frequency"))
        self.RequestCurrentFrequencypushButton.setText(_translate("MainWindow", "Request Current\n"
                                                                                "Frequency"))
        self.aaa.setTabText(self.aaa.indexOf(self.OutputFrequencySettingTab),
                            _translate("MainWindow", "Output Frequency Setting"))
        self.label_4.setText(_translate("MainWindow", "Signal type:"))
        self.SignalTypecomboBox.setItemText(1, _translate("MainWindow", "sin"))
        self.SignalTypecomboBox.setItemText(2, _translate("MainWindow", "user signal"))
        self.SignalTypecomboBox.setItemText(3, _translate("MainWindow", "dynamic points density"))
        self.AccelerationTimelabel_2.setText(_translate("MainWindow", "Acceleration\n"
                                                                      "Deceleration\n"
                                                                      " Regime:"))
        self.AccDec1radioButton.setText(_translate("MainWindow", "1"))
        self.AccDec2radioButton.setText(_translate("MainWindow", "2"))
        self.AccDec3radioButton.setText(_translate("MainWindow", "3"))
        self.AccDec4radioButton.setText(_translate("MainWindow", "4"))
        self.aaa.setTabText(self.aaa.indexOf(self.FrequencySignalSetting),
                            _translate("MainWindow", "Frequency Signal Setting"))
        self.pushButtonStartSignalSending.setText(_translate("MainWindow", "Start Signal Sending"))
        self.PauseSendingradioButton.setText(_translate("MainWindow", "Pause"))
        self.ResumeSendingradioButton.setText(_translate("MainWindow", "Resume"))
        self.pushButtonStopSignalSending.setText(_translate("MainWindow", "Stop Signal Sending"))
        self.EndlessSendingcheckBox.setText(_translate("MainWindow", "Send Pattern Continuously"))
        self.aaa.setTabText(self.aaa.indexOf(self.SignalSendingTab),
                            _translate("MainWindow", "Signal Sending to Delta PC"))
        self.menuConnection_Parameters.setTitle(_translate("MainWindow", "Connection Parameters"))
        self.menuOutput_Frequency_Settings.setTitle(_translate("MainWindow", "Output Frequency Settings"))
        self.menuNew.setTitle(_translate("MainWindow", "New"))