from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EdgeSignalWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 850)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 850))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(600, 400))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(700, 130))
        self.frame_3.setMaximumSize(QtCore.QSize(1500, 200))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ConfigFilenamelabel = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ConfigFilenamelabel.setFont(font)
        self.ConfigFilenamelabel.setLineWidth(4)
        self.ConfigFilenamelabel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ConfigFilenamelabel.setObjectName("ConfigFilenamelabel")
        self.horizontalLayout.addWidget(self.ConfigFilenamelabel)
        self.ConfigFileNamelineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.ConfigFileNamelineEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.ConfigFileNamelineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ConfigFileNamelineEdit.setFont(font)
        self.ConfigFileNamelineEdit.setObjectName("ConfigFileNamelineEdit")
        self.horizontalLayout.addWidget(self.ConfigFileNamelineEdit)
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.AutoFillpushButton = QtWidgets.QPushButton(self.frame_8)
        self.AutoFillpushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.AutoFillpushButton.setObjectName("AutoFillpushButton")
        self.gridLayout_10.addWidget(self.AutoFillpushButton, 0, 0, 1, 2)
        self.SavePresetpushButton = QtWidgets.QPushButton(self.frame_8)
        self.SavePresetpushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.SavePresetpushButton.setObjectName("SavePresetpushButton")
        self.gridLayout_10.addWidget(self.SavePresetpushButton, 1, 0, 1, 1)
        self.DeletePresetpushButton = QtWidgets.QPushButton(self.frame_8)
        self.DeletePresetpushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.DeletePresetpushButton.setObjectName("DeletePresetpushButton")
        self.gridLayout_10.addWidget(self.DeletePresetpushButton, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.frame_8)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lcdNumber = QtWidgets.QLCDNumber(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber.sizePolicy().hasHeightForWidth())
        self.lcdNumber.setSizePolicy(sizePolicy)
        self.lcdNumber.setMinimumSize(QtCore.QSize(80, 20))
        self.lcdNumber.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout.addWidget(self.lcdNumber)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.LogFilenamelineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.LogFilenamelineEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.LogFilenamelineEdit.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.LogFilenamelineEdit.setFont(font)
        self.LogFilenamelineEdit.setObjectName("LogFilenamelineEdit")
        self.horizontalLayout.addWidget(self.LogFilenamelineEdit)
        self.gridLayout_3.addWidget(self.frame_3, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMinimumSize(QtCore.QSize(400, 600))
        self.frame_7.setMaximumSize(QtCore.QSize(500, 600))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(300, 300))
        self.frame.setMaximumSize(QtCore.QSize(500, 400))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelStartTime = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelStartTime.sizePolicy().hasHeightForWidth())
        self.labelStartTime.setSizePolicy(sizePolicy)
        self.labelStartTime.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.labelStartTime.setObjectName("labelStartTime")
        self.gridLayout.addWidget(self.labelStartTime, 0, 0, 1, 1)
        self.labelEndTime_2 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelEndTime_2.sizePolicy().hasHeightForWidth())
        self.labelEndTime_2.setSizePolicy(sizePolicy)
        self.labelEndTime_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.labelEndTime_2.setObjectName("labelEndTime_2")
        self.gridLayout.addWidget(self.labelEndTime_2, 8, 0, 1, 1)
        self.RequestFrequencyhorizontalSlider = QtWidgets.QSlider(self.frame)
        self.RequestFrequencyhorizontalSlider.setMaximumSize(QtCore.QSize(500, 16777215))
        self.RequestFrequencyhorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.RequestFrequencyhorizontalSlider.setObjectName("RequestFrequencyhorizontalSlider")
        self.gridLayout.addWidget(self.RequestFrequencyhorizontalSlider, 8, 1, 1, 1)
        self.HighLevelFrequencylineEdit = QtWidgets.QLineEdit(self.frame)
        self.HighLevelFrequencylineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.HighLevelFrequencylineEdit.setObjectName("HighLevelFrequencylineEdit")
        self.gridLayout.addWidget(self.HighLevelFrequencylineEdit, 5, 2, 1, 1)
        self.AccelerationTimelineEdit = QtWidgets.QLineEdit(self.frame)
        self.AccelerationTimelineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.AccelerationTimelineEdit.setObjectName("AccelerationTimelineEdit")
        self.gridLayout.addWidget(self.AccelerationTimelineEdit, 1, 2, 1, 1)
        self.PlateauTimelineEdit = QtWidgets.QLineEdit(self.frame)
        self.PlateauTimelineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.PlateauTimelineEdit.setObjectName("PlateauTimelineEdit")
        self.gridLayout.addWidget(self.PlateauTimelineEdit, 2, 2, 1, 1)
        self.labeLowLevelFrequency = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labeLowLevelFrequency.sizePolicy().hasHeightForWidth())
        self.labeLowLevelFrequency.setSizePolicy(sizePolicy)
        self.labeLowLevelFrequency.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.labeLowLevelFrequency.setObjectName("labeLowLevelFrequency")
        self.gridLayout.addWidget(self.labeLowLevelFrequency, 4, 0, 1, 1)
        self.AccelerationTimehorizontalSlider = QtWidgets.QSlider(self.frame)
        self.AccelerationTimehorizontalSlider.setMaximumSize(QtCore.QSize(500, 16777215))
        self.AccelerationTimehorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.AccelerationTimehorizontalSlider.setObjectName("AccelerationTimehorizontalSlider")
        self.gridLayout.addWidget(self.AccelerationTimehorizontalSlider, 1, 1, 1, 1)
        self.RequestFrequencylineEdit = QtWidgets.QLineEdit(self.frame)
        self.RequestFrequencylineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.RequestFrequencylineEdit.setObjectName("RequestFrequencylineEdit")
        self.gridLayout.addWidget(self.RequestFrequencylineEdit, 8, 2, 1, 1)
        self.labelPlateauTime = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPlateauTime.sizePolicy().hasHeightForWidth())
        self.labelPlateauTime.setSizePolicy(sizePolicy)
        self.labelPlateauTime.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.labelPlateauTime.setObjectName("labelPlateauTime")
        self.gridLayout.addWidget(self.labelPlateauTime, 2, 0, 1, 1)
        self.labelEndTime = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelEndTime.sizePolicy().hasHeightForWidth())
        self.labelEndTime.setSizePolicy(sizePolicy)
        self.labelEndTime.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.labelEndTime.setObjectName("labelEndTime")
        self.gridLayout.addWidget(self.labelEndTime, 6, 0, 1, 1)
        self.DecelerationTimelineEdit = QtWidgets.QLineEdit(self.frame)
        self.DecelerationTimelineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.DecelerationTimelineEdit.setObjectName("DecelerationTimelineEdit")
        self.gridLayout.addWidget(self.DecelerationTimelineEdit, 3, 2, 1, 1)
        self.PlateauTimehorizontalSlider = QtWidgets.QSlider(self.frame)
        self.PlateauTimehorizontalSlider.setMaximumSize(QtCore.QSize(500, 16777215))
        self.PlateauTimehorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.PlateauTimehorizontalSlider.setObjectName("PlateauTimehorizontalSlider")
        self.gridLayout.addWidget(self.PlateauTimehorizontalSlider, 2, 1, 1, 1)
        self.EndTimehorizontalSlider = QtWidgets.QSlider(self.frame)
        self.EndTimehorizontalSlider.setMaximumSize(QtCore.QSize(500, 16777215))
        self.EndTimehorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.EndTimehorizontalSlider.setObjectName("EndTimehorizontalSlider")
        self.gridLayout.addWidget(self.EndTimehorizontalSlider, 6, 1, 1, 1)
        self.labelAccelerationTime = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelAccelerationTime.sizePolicy().hasHeightForWidth())
        self.labelAccelerationTime.setSizePolicy(sizePolicy)
        self.labelAccelerationTime.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.labelAccelerationTime.setObjectName("labelAccelerationTime")
        self.gridLayout.addWidget(self.labelAccelerationTime, 1, 0, 1, 1)
        self.HighLevelFrequencyhorizontalSlider = QtWidgets.QSlider(self.frame)
        self.HighLevelFrequencyhorizontalSlider.setMaximumSize(QtCore.QSize(500, 16777215))
        self.HighLevelFrequencyhorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.HighLevelFrequencyhorizontalSlider.setObjectName("HighLevelFrequencyhorizontalSlider")
        self.gridLayout.addWidget(self.HighLevelFrequencyhorizontalSlider, 5, 1, 1, 1)
        self.DecelerationTimehorizontalSlider = QtWidgets.QSlider(self.frame)
        self.DecelerationTimehorizontalSlider.setMaximumSize(QtCore.QSize(500, 16777215))
        self.DecelerationTimehorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.DecelerationTimehorizontalSlider.setObjectName("DecelerationTimehorizontalSlider")
        self.gridLayout.addWidget(self.DecelerationTimehorizontalSlider, 3, 1, 1, 1)
        self.labelHighLevelFrequency = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHighLevelFrequency.sizePolicy().hasHeightForWidth())
        self.labelHighLevelFrequency.setSizePolicy(sizePolicy)
        self.labelHighLevelFrequency.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.labelHighLevelFrequency.setObjectName("labelHighLevelFrequency")
        self.gridLayout.addWidget(self.labelHighLevelFrequency, 5, 0, 1, 1)
        self.LowLevelFrequencylineEdit = QtWidgets.QLineEdit(self.frame)
        self.LowLevelFrequencylineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.LowLevelFrequencylineEdit.setObjectName("LowLevelFrequencylineEdit")
        self.gridLayout.addWidget(self.LowLevelFrequencylineEdit, 4, 2, 1, 1)
        self.EndTimelineEdit = QtWidgets.QLineEdit(self.frame)
        self.EndTimelineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.EndTimelineEdit.setObjectName("EndTimelineEdit")
        self.gridLayout.addWidget(self.EndTimelineEdit, 6, 2, 1, 1)
        self.labelDecelerationTime = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDecelerationTime.sizePolicy().hasHeightForWidth())
        self.labelDecelerationTime.setSizePolicy(sizePolicy)
        self.labelDecelerationTime.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.labelDecelerationTime.setObjectName("labelDecelerationTime")
        self.gridLayout.addWidget(self.labelDecelerationTime, 3, 0, 1, 1)
        self.StartTimelineEdit = QtWidgets.QLineEdit(self.frame)
        self.StartTimelineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.StartTimelineEdit.setObjectName("StartTimelineEdit")
        self.gridLayout.addWidget(self.StartTimelineEdit, 0, 2, 1, 1)
        self.LowLevelFrequencyhorizontalSlider = QtWidgets.QSlider(self.frame)
        self.LowLevelFrequencyhorizontalSlider.setMaximumSize(QtCore.QSize(500, 16777215))
        self.LowLevelFrequencyhorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.LowLevelFrequencyhorizontalSlider.setObjectName("LowLevelFrequencyhorizontalSlider")
        self.gridLayout.addWidget(self.LowLevelFrequencyhorizontalSlider, 4, 1, 1, 1)
        self.StartTimehorizontalSlider = QtWidgets.QSlider(self.frame)
        self.StartTimehorizontalSlider.setMaximumSize(QtCore.QSize(500, 16777215))
        self.StartTimehorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.StartTimehorizontalSlider.setObjectName("StartTimehorizontalSlider")
        self.gridLayout.addWidget(self.StartTimehorizontalSlider, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame_7)
        self.frame_4.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(500, 150))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButtonStartSignalSending = QtWidgets.QPushButton(self.frame_5)
        self.pushButtonStartSignalSending.setMinimumSize(QtCore.QSize(60, 0))
        self.pushButtonStartSignalSending.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonStartSignalSending.setObjectName("pushButtonStartSignalSending")
        self.gridLayout_6.addWidget(self.pushButtonStartSignalSending, 0, 0, 1, 2)
        self.PauseSendingradioButton = QtWidgets.QRadioButton(self.frame_5)
        self.PauseSendingradioButton.setObjectName("PauseSendingradioButton")
        self.gridLayout_6.addWidget(self.PauseSendingradioButton, 1, 0, 1, 1)
        self.ResumeSendingradioButton = QtWidgets.QRadioButton(self.frame_5)
        self.ResumeSendingradioButton.setChecked(True)
        self.ResumeSendingradioButton.setAutoExclusive(True)
        self.ResumeSendingradioButton.setObjectName("ResumeSendingradioButton")
        self.gridLayout_6.addWidget(self.ResumeSendingradioButton, 1, 1, 1, 1)
        self.pushButtonStopSignalSending = QtWidgets.QPushButton(self.frame_5)
        self.pushButtonStopSignalSending.setMinimumSize(QtCore.QSize(60, 0))
        self.pushButtonStopSignalSending.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonStopSignalSending.setObjectName("pushButtonStopSignalSending")
        self.gridLayout_6.addWidget(self.pushButtonStopSignalSending, 2, 0, 1, 2)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.EndlessSendingradioButton = QtWidgets.QRadioButton(self.frame_6)
        self.EndlessSendingradioButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.EndlessSendingradioButton.setObjectName("EndlessSendingradioButton")
        self.gridLayout_4.addWidget(self.EndlessSendingradioButton, 0, 0, 1, 2)
        self.SendCyclesradioButton = QtWidgets.QRadioButton(self.frame_6)
        self.SendCyclesradioButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.SendCyclesradioButton.setChecked(True)
        self.SendCyclesradioButton.setObjectName("SendCyclesradioButton")
        self.gridLayout_4.addWidget(self.SendCyclesradioButton, 1, 0, 1, 2)
        self.CyclesNumberspinBox = QtWidgets.QSpinBox(self.frame_6)
        self.CyclesNumberspinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.CyclesNumberspinBox.setMinimum(1)
        self.CyclesNumberspinBox.setMaximum(100)
        self.CyclesNumberspinBox.setObjectName("CyclesNumberspinBox")
        self.gridLayout_4.addWidget(self.CyclesNumberspinBox, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_6)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 2, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.gridLayout_9.addWidget(self.frame_4, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_7, 0, 0, 3, 1)
        self.plot_widget = PlotCanvas(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_widget.sizePolicy().hasHeightForWidth())
        self.plot_widget.setSizePolicy(sizePolicy)
        self.plot_widget.setMinimumSize(QtCore.QSize(300, 200))
        # self.plot_widget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        # self.plot_widget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plot_widget.setObjectName("plot_widget")
        self.gridLayout_5.addWidget(self.plot_widget, 0, 1, 3, 1)
        self.gridLayout_3.addWidget(self.frame_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ConfigFilenamelabel.setText(_translate("MainWindow", "Config Filename:"))
        self.AutoFillpushButton.setText(_translate("MainWindow", "Auto-Fill"))
        self.SavePresetpushButton.setText(_translate("MainWindow", "Save\n"
                                                                   "preset"))
        self.DeletePresetpushButton.setText(_translate("MainWindow", "Delete\n"
                                                                     "preset"))
        self.label_2.setText(_translate("MainWindow", "Current Cycle №:"))
        self.label_3.setText(_translate("MainWindow", "Log filename:"))
        self.LogFilenamelineEdit.setText(_translate("MainWindow", "SendingLogs/Default"))
        self.labelStartTime.setText(_translate("MainWindow", "Start Time:"))
        self.labelEndTime_2.setText(_translate("MainWindow", "Request Frequency:"))
        self.labeLowLevelFrequency.setText(_translate("MainWindow", "Low-level Frequency:"))
        self.labelPlateauTime.setText(_translate("MainWindow", "Plateau Time:"))
        self.labelEndTime.setText(_translate("MainWindow", "End Time:"))
        self.labelAccelerationTime.setText(_translate("MainWindow", "Acceleration Time:"))
        self.labelHighLevelFrequency.setText(_translate("MainWindow", "High-level Frequency:"))
        self.labelDecelerationTime.setText(_translate("MainWindow", "Deceleration Time:"))
        self.pushButtonStartSignalSending.setText(_translate("MainWindow", "Start"))
        self.PauseSendingradioButton.setText(_translate("MainWindow", "Pause"))
        self.ResumeSendingradioButton.setText(_translate("MainWindow", "Resume"))
        self.pushButtonStopSignalSending.setText(_translate("MainWindow", "Stop"))
        self.EndlessSendingradioButton.setText(_translate("MainWindow", "Send Continuously"))
        self.SendCyclesradioButton.setText(_translate("MainWindow", "Send Cycles"))
        self.label.setText(_translate("MainWindow", "Cycles №"))


from PlotCanvas import PlotCanvas
