from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SinusMainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 610)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(500, 500))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelPhase = QtWidgets.QLabel(self.frame_2)
        self.labelPhase.setObjectName("labelPhase")
        self.gridLayout.addWidget(self.labelPhase, 0, 0, 1, 1)
        self.horizontalSliderPhase = QtWidgets.QSlider(self.frame_2)
        self.horizontalSliderPhase.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderPhase.setObjectName("horizontalSliderPhase")
        self.gridLayout.addWidget(self.horizontalSliderPhase, 0, 1, 1, 1)
        self.PhaselineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.PhaselineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.PhaselineEdit.setObjectName("PhaselineEdit")
        self.gridLayout.addWidget(self.PhaselineEdit, 0, 2, 1, 1)
        self.labelOmega = QtWidgets.QLabel(self.frame_2)
        self.labelOmega.setObjectName("labelOmega")
        self.gridLayout.addWidget(self.labelOmega, 1, 0, 1, 1)
        self.horizontalSliderOmega = QtWidgets.QSlider(self.frame_2)
        self.horizontalSliderOmega.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderOmega.setObjectName("horizontalSliderOmega")
        self.gridLayout.addWidget(self.horizontalSliderOmega, 1, 1, 1, 1)
        self.OmegalineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.OmegalineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.OmegalineEdit.setObjectName("OmegalineEdit")
        self.gridLayout.addWidget(self.OmegalineEdit, 1, 2, 1, 1)
        self.labelPointsNumber = QtWidgets.QLabel(self.frame_2)
        self.labelPointsNumber.setObjectName("labelPointsNumber")
        self.gridLayout.addWidget(self.labelPointsNumber, 2, 0, 1, 1)
        self.horizontalSliderPointsNumber = QtWidgets.QSlider(self.frame_2)
        self.horizontalSliderPointsNumber.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderPointsNumber.setObjectName("horizontalSliderPointsNumber")
        self.gridLayout.addWidget(self.horizontalSliderPointsNumber, 2, 1, 1, 1)
        self.PointsNumberlineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.PointsNumberlineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.PointsNumberlineEdit.setObjectName("PointsNumberlineEdit")
        self.gridLayout.addWidget(self.PointsNumberlineEdit, 2, 2, 1, 1)
        self.labelTimeFrom = QtWidgets.QLabel(self.frame_2)
        self.labelTimeFrom.setObjectName("labelTimeFrom")
        self.gridLayout.addWidget(self.labelTimeFrom, 3, 0, 1, 1)
        self.horizontalSliderTimeFrom = QtWidgets.QSlider(self.frame_2)
        self.horizontalSliderTimeFrom.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderTimeFrom.setObjectName("horizontalSliderTimeFrom")
        self.gridLayout.addWidget(self.horizontalSliderTimeFrom, 3, 1, 1, 1)
        self.TimeFromlineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.TimeFromlineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TimeFromlineEdit.setObjectName("TimeFromlineEdit")
        self.gridLayout.addWidget(self.TimeFromlineEdit, 3, 2, 1, 1)
        self.labelTimeTo = QtWidgets.QLabel(self.frame_2)
        self.labelTimeTo.setObjectName("labelTimeTo")
        self.gridLayout.addWidget(self.labelTimeTo, 4, 0, 1, 1)
        self.horizontalSliderTimeTo = QtWidgets.QSlider(self.frame_2)
        self.horizontalSliderTimeTo.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderTimeTo.setObjectName("horizontalSliderTimeTo")
        self.gridLayout.addWidget(self.horizontalSliderTimeTo, 4, 1, 1, 1)
        self.TimeTolineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.TimeTolineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TimeTolineEdit.setObjectName("TimeTolineEdit")
        self.gridLayout.addWidget(self.TimeTolineEdit, 4, 2, 1, 1)
        self.labelAmplitude = QtWidgets.QLabel(self.frame_2)
        self.labelAmplitude.setObjectName("labelAmplitude")
        self.gridLayout.addWidget(self.labelAmplitude, 5, 0, 1, 1)
        self.horizontalSliderAmplitude = QtWidgets.QSlider(self.frame_2)
        self.horizontalSliderAmplitude.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderAmplitude.setObjectName("horizontalSliderAmplitude")
        self.gridLayout.addWidget(self.horizontalSliderAmplitude, 5, 1, 1, 1)
        self.AmplitudelineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.AmplitudelineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.AmplitudelineEdit.setObjectName("AmplitudelineEdit")
        self.gridLayout.addWidget(self.AmplitudelineEdit, 5, 2, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = PlotCanvas(self.centralwidget)
        #self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        #self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelPhase.setText(_translate("MainWindow", "Phase:"))
        self.labelOmega.setText(_translate("MainWindow", "Omega:"))
        self.labelPointsNumber.setText(_translate("MainWindow", "Points Number:"))
        self.labelTimeFrom.setText(_translate("MainWindow", "Time From:"))
        self.labelTimeTo.setText(_translate("MainWindow", "Time To:"))
        self.labelAmplitude.setText(_translate("MainWindow", "Amplitude:"))
from PlotCanvas import PlotCanvas


