from PyQt5 import QtCore
from PyQt5 import QtWidgets

class Ui_SinusMainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(569, 745)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(39, 29, 88, 181))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.labelPhase = QtWidgets.QLabel(self.splitter)
        self.labelPhase.setObjectName("labelPhase")
        self.labelOmega = QtWidgets.QLabel(self.splitter)
        self.labelOmega.setObjectName("labelOmega")
        self.labelPointsNumber = QtWidgets.QLabel(self.splitter)
        self.labelPointsNumber.setObjectName("labelPointsNumber")
        self.labelTimeFrom = QtWidgets.QLabel(self.splitter)
        self.labelTimeFrom.setObjectName("labelTimeFrom")
        self.labelTimeTo = QtWidgets.QLabel(self.splitter)
        self.labelTimeTo.setObjectName("labelTimeTo")
        self.labelAmplitude = QtWidgets.QLabel(self.splitter)
        self.labelAmplitude.setObjectName("labelAmplitude")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(149, 29, 251, 181))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.horizontalSliderPhase = QtWidgets.QSlider(self.splitter_2)
        self.horizontalSliderPhase.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderPhase.setObjectName("horizontalSliderPhase")
        self.horizontalSliderOmega = QtWidgets.QSlider(self.splitter_2)
        self.horizontalSliderOmega.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderOmega.setObjectName("horizontalSliderOmega")
        self.horizontalSliderPointsNumber = QtWidgets.QSlider(self.splitter_2)
        self.horizontalSliderPointsNumber.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderPointsNumber.setObjectName("horizontalSliderPointsNumber")
        self.horizontalSliderTimeFrom = QtWidgets.QSlider(self.splitter_2)
        self.horizontalSliderTimeFrom.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderTimeFrom.setObjectName("horizontalSliderTimeFrom")
        self.horizontalSliderTimeTo = QtWidgets.QSlider(self.splitter_2)
        self.horizontalSliderTimeTo.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderTimeTo.setObjectName("horizontalSliderTimeTo")
        self.horizontalSliderAmplitude = QtWidgets.QSlider(self.splitter_2)
        self.horizontalSliderAmplitude.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderAmplitude.setObjectName("horizontalSliderAmplitude")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setGeometry(QtCore.QRect(450, 30, 61, 181))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.PhaselineEdit = QtWidgets.QLineEdit(self.splitter_3)
        self.PhaselineEdit.setObjectName("PhaselineEdit")
        self.OmegalineEdit = QtWidgets.QLineEdit(self.splitter_3)
        self.OmegalineEdit.setObjectName("OmegalineEdit")
        self.PointsNumberlineEdit = QtWidgets.QLineEdit(self.splitter_3)
        self.PointsNumberlineEdit.setObjectName("PointsNumberlineEdit")
        self.TimeFromlineEdit = QtWidgets.QLineEdit(self.splitter_3)
        self.TimeFromlineEdit.setObjectName("TimeFromlineEdit")
        self.TimeTolineEdit = QtWidgets.QLineEdit(self.splitter_3)
        self.TimeTolineEdit.setObjectName("TimeTolineEdit")
        self.AmplitudelineEdit = QtWidgets.QLineEdit(self.splitter_3)
        self.AmplitudelineEdit.setObjectName("AmplitudelineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 569, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelPhase.setText(_translate("MainWindow", "Phase:"))
        self.labelOmega.setText(_translate("MainWindow", "Omega:"))
        self.labelPointsNumber.setText(_translate("MainWindow", "Points Number:"))
        self.labelTimeFrom.setText(_translate("MainWindow", "Time From:"))
        self.labelTimeTo.setText(_translate("MainWindow", "Time To:"))
        self.labelAmplitude.setText(_translate("MainWindow", "Amplitude:"))

