from PyQt5 import QtCore
from PyQt5 import QtWidgets

class Ui_SinWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEditSliderTimeFromMin = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSliderTimeFromMin.setGeometry(QtCore.QRect(410, 150, 31, 31))
        self.lineEditSliderTimeFromMin.setObjectName("lineEditSliderTimeFromMin")
        self.lineEditSliderTimeFromMax = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSliderTimeFromMax.setGeometry(QtCore.QRect(680, 150, 31, 31))
        self.lineEditSliderTimeFromMax.setObjectName("lineEditSliderTimeFromMax")
        self.lineEditSliderTimeToMin = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSliderTimeToMin.setGeometry(QtCore.QRect(410, 190, 31, 31))
        self.lineEditSliderTimeToMin.setObjectName("lineEditSliderTimeToMin")
        self.lineEditSliderAmplitudeMin = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSliderAmplitudeMin.setGeometry(QtCore.QRect(410, 230, 31, 31))
        self.lineEditSliderAmplitudeMin.setObjectName("lineEditSliderAmplitudeMin")
        self.lineEditSliderTimeToMax = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSliderTimeToMax.setGeometry(QtCore.QRect(680, 190, 31, 31))
        self.lineEditSliderTimeToMax.setObjectName("lineEditSliderTimeToMax")
        self.lineEditSliderAmplitudeMax = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSliderAmplitudeMax.setGeometry(QtCore.QRect(680, 230, 31, 31))
        self.lineEditSliderAmplitudeMax.setObjectName("lineEditSliderAmplitudeMax")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(450, 150, 221, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalSliderTimeFrom = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSliderTimeFrom.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderTimeFrom.setObjectName("horizontalSliderTimeFrom")
        self.verticalLayout_3.addWidget(self.horizontalSliderTimeFrom)
        self.horizontalSliderTimeTo = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSliderTimeTo.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderTimeTo.setObjectName("horizontalSliderTimeTo")
        self.verticalLayout_3.addWidget(self.horizontalSliderTimeTo)
        self.horizontalSliderAmplitude = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSliderAmplitude.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderAmplitude.setObjectName("horizontalSliderAmplitude")
        self.verticalLayout_3.addWidget(self.horizontalSliderAmplitude)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(110, 90, 238, 187))
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelPhase = QtWidgets.QLabel(self.widget)
        self.labelPhase.setObjectName("labelPhase")
        self.gridLayout_2.addWidget(self.labelPhase, 0, 0, 1, 1)
        self.lineEditPhase = QtWidgets.QLineEdit(self.widget)
        self.lineEditPhase.setObjectName("lineEditPhase")
        self.gridLayout_2.addWidget(self.lineEditPhase, 0, 1, 1, 1)
        self.labelOmega = QtWidgets.QLabel(self.widget)
        self.labelOmega.setObjectName("labelOmega")
        self.gridLayout_2.addWidget(self.labelOmega, 1, 0, 1, 1)
        self.lineEditOmega = QtWidgets.QLineEdit(self.widget)
        self.lineEditOmega.setObjectName("lineEditOmega")
        self.gridLayout_2.addWidget(self.lineEditOmega, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelPointsNumber = QtWidgets.QLabel(self.widget)
        self.labelPointsNumber.setObjectName("labelPointsNumber")
        self.gridLayout.addWidget(self.labelPointsNumber, 0, 0, 1, 1)
        self.lineEditPointsNumber = QtWidgets.QLineEdit(self.widget)
        self.lineEditPointsNumber.setObjectName("lineEditPointsNumber")
        self.gridLayout.addWidget(self.lineEditPointsNumber, 0, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelTimeFrom = QtWidgets.QLabel(self.widget)
        self.labelTimeFrom.setObjectName("labelTimeFrom")
        self.verticalLayout_2.addWidget(self.labelTimeFrom)
        self.labelTimeTo = QtWidgets.QLabel(self.widget)
        self.labelTimeTo.setObjectName("labelTimeTo")
        self.verticalLayout_2.addWidget(self.labelTimeTo)
        self.labelAmplitude = QtWidgets.QLabel(self.widget)
        self.labelAmplitude.setObjectName("labelAmplitude")
        self.verticalLayout_2.addWidget(self.labelAmplitude)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEditTimeFrom = QtWidgets.QLineEdit(self.widget)
        self.lineEditTimeFrom.setObjectName("lineEditTimeFrom")
        self.verticalLayout.addWidget(self.lineEditTimeFrom)
        self.lineEditTimeTo = QtWidgets.QLineEdit(self.widget)
        self.lineEditTimeTo.setObjectName("lineEditTimeTo")
        self.verticalLayout.addWidget(self.lineEditTimeTo)
        self.lineEditAmplitude = QtWidgets.QLineEdit(self.widget)
        self.lineEditAmplitude.setObjectName("lineEditAmplitude")
        self.verticalLayout.addWidget(self.lineEditAmplitude)
        self.gridLayout.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEditSliderTimeFromMin.setText(_translate("MainWindow", "0.0"))
        self.lineEditSliderTimeFromMax.setText(_translate("MainWindow", "600"))
        self.lineEditSliderAmplitudeMin.setText(_translate("MainWindow", "0.0"))
        self.lineEditSliderAmplitudeMax.setText(_translate("MainWindow", "10.0"))
        self.labelPhase.setText(_translate("MainWindow", "Phase:"))
        self.labelOmega.setText(_translate("MainWindow", "Omega:"))
        self.labelPointsNumber.setText(_translate("MainWindow", "Points Number:"))
        self.labelTimeFrom.setText(_translate("MainWindow", "Time From:"))
        self.labelTimeTo.setText(_translate("MainWindow", "Time To:"))
        self.labelAmplitude.setText(_translate("MainWindow", "Amplitude:"))


