from PyQt5 import QtCore
from PyQt5 import QtWidgets

class Ui_SinWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 50, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelVerticalOffset = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelVerticalOffset.setObjectName("labelVerticalOffset")
        self.verticalLayout.addWidget(self.labelVerticalOffset)
        self.labelFrequency = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelFrequency.setObjectName("labelFrequency")
        self.verticalLayout.addWidget(self.labelFrequency)
        self.labelAmplitude = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelAmplitude.setObjectName("labelAmplitude")
        self.verticalLayout.addWidget(self.labelAmplitude)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(290, 50, 160, 88))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEditVerticalOffset = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditVerticalOffset.setObjectName("lineEditVerticalOffset")
        self.verticalLayout_3.addWidget(self.lineEditVerticalOffset)
        self.lineEditFrequency = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditFrequency.setObjectName("lineEditFrequency")
        self.verticalLayout_3.addWidget(self.lineEditFrequency)
        self.lineEditAmplitude = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditAmplitude.setObjectName("lineEditAmplitude")
        self.verticalLayout_3.addWidget(self.lineEditAmplitude)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(490, 50, 160, 82))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalSliderVerticalOffset = QtWidgets.QSlider(self.verticalLayoutWidget_3)
        self.horizontalSliderVerticalOffset.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderVerticalOffset.setObjectName("horizontalSliderVerticalOffset")
        self.verticalLayout_4.addWidget(self.horizontalSliderVerticalOffset)
        self.horizontalSliderFrequency = QtWidgets.QSlider(self.verticalLayoutWidget_3)
        self.horizontalSliderFrequency.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderFrequency.setObjectName("horizontalSliderFrequency")
        self.verticalLayout_4.addWidget(self.horizontalSliderFrequency)
        self.horizontalSliderAmplitude = QtWidgets.QSlider(self.verticalLayoutWidget_3)
        self.horizontalSliderAmplitude.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderAmplitude.setObjectName("horizontalSliderAmplitude")
        self.verticalLayout_4.addWidget(self.horizontalSliderAmplitude)
        self.TestpushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.TestpushButton1.setGeometry(QtCore.QRect(110, 330, 93, 28))
        self.TestpushButton1.setObjectName("TestpushButton1")
        self.TestpushButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.TestpushButton2.setGeometry(QtCore.QRect(270, 330, 93, 28))
        self.TestpushButton2.setObjectName("TestpushButton2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(290, 150, 161, 121))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEditPhase = QtWidgets.QLineEdit(self.widget)
        self.lineEditPhase.setObjectName("lineEditPhase")
        self.verticalLayout_2.addWidget(self.lineEditPhase)
        self.lineEditPeriodStart = QtWidgets.QLineEdit(self.widget)
        self.lineEditPeriodStart.setObjectName("lineEditPeriodStart")
        self.verticalLayout_2.addWidget(self.lineEditPeriodStart)
        self.lineEditPeriodEnd = QtWidgets.QLineEdit(self.widget)
        self.lineEditPeriodEnd.setObjectName("lineEditPeriodEnd")
        self.verticalLayout_2.addWidget(self.lineEditPeriodEnd)
        self.lineEditNumberOfPoints = QtWidgets.QLineEdit(self.widget)
        self.lineEditNumberOfPoints.setObjectName("lineEditNumberOfPoints")
        self.verticalLayout_2.addWidget(self.lineEditNumberOfPoints)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(490, 150, 161, 121))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalSliderPhase = QtWidgets.QSlider(self.widget1)
        self.horizontalSliderPhase.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderPhase.setObjectName("horizontalSliderPhase")
        self.verticalLayout_5.addWidget(self.horizontalSliderPhase)
        self.horizontalSliderPeriodStart = QtWidgets.QSlider(self.widget1)
        self.horizontalSliderPeriodStart.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderPeriodStart.setObjectName("horizontalSliderPeriodStart")
        self.verticalLayout_5.addWidget(self.horizontalSliderPeriodStart)
        self.horizontalSliderPeriodEnd = QtWidgets.QSlider(self.widget1)
        self.horizontalSliderPeriodEnd.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderPeriodEnd.setObjectName("horizontalSliderPeriodEnd")
        self.verticalLayout_5.addWidget(self.horizontalSliderPeriodEnd)
        self.horizontalSliderNumberOfPoints = QtWidgets.QSlider(self.widget1)
        self.horizontalSliderNumberOfPoints.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderNumberOfPoints.setObjectName("horizontalSliderNumberOfPoints")
        self.verticalLayout_5.addWidget(self.horizontalSliderNumberOfPoints)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(90, 150, 121, 121))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.widget2)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelVerticalOffset.setText(_translate("MainWindow", "Vertical offset"))
        self.labelFrequency.setText(_translate("MainWindow", "Frequency (w)"))
        self.labelAmplitude.setText(_translate("MainWindow", "Amplitude"))
        self.TestpushButton1.setText(_translate("MainWindow", "PushButton1"))
        self.TestpushButton2.setText(_translate("MainWindow", "PushButton2"))
        self.label.setText(_translate("MainWindow", "Phase"))
        self.label_2.setText(_translate("MainWindow", "Period Start"))
        self.label_3.setText(_translate("MainWindow", "Period End"))
        self.label_4.setText(_translate("MainWindow", "Number of Points"))

