from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SinusMainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 633)
        MainWindow.setMinimumSize(QtCore.QSize(0, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(500, 400))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = PlotCanvas(self.centralwidget)
        # self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setObjectName("frame")
        self.gridLayout_4.addWidget(self.frame, 1, 1, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(400, 100))
        self.frame_5.setMaximumSize(QtCore.QSize(400, 400))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelPhase = QtWidgets.QLabel(self.frame_2)
        self.labelPhase.setObjectName("labelPhase")
        self.gridLayout.addWidget(self.labelPhase, 0, 0, 1, 1)
        self.horizontalSliderPhase = QtWidgets.QSlider(self.frame_2)
        self.horizontalSliderPhase.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderPhase.setObjectName("horizontalSliderPhase")
        self.gridLayout.addWidget(self.horizontalSliderPhase, 0, 1, 1, 1)
        self.PhaselineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.PhaselineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.PhaselineEdit.setObjectName("PhaselineEdit")
        self.gridLayout.addWidget(self.PhaselineEdit, 0, 2, 1, 1)
        self.labelOmega = QtWidgets.QLabel(self.frame_2)
        self.labelOmega.setObjectName("labelOmega")
        self.gridLayout.addWidget(self.labelOmega, 1, 0, 1, 1)
        self.horizontalSliderOmega = QtWidgets.QSlider(self.frame_2)
        self.horizontalSliderOmega.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderOmega.setObjectName("horizontalSliderOmega")
        self.gridLayout.addWidget(self.horizontalSliderOmega, 1, 1, 1, 1)
        self.OmegalineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.OmegalineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.OmegalineEdit.setObjectName("OmegalineEdit")
        self.gridLayout.addWidget(self.OmegalineEdit, 1, 2, 1, 1)
        self.labelPointsNumber = QtWidgets.QLabel(self.frame_2)
        self.labelPointsNumber.setObjectName("labelPointsNumber")
        self.gridLayout.addWidget(self.labelPointsNumber, 2, 0, 1, 1)
        self.horizontalSliderPointsNumber = QtWidgets.QSlider(self.frame_2)
        self.horizontalSliderPointsNumber.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderPointsNumber.setObjectName("horizontalSliderPointsNumber")
        self.gridLayout.addWidget(self.horizontalSliderPointsNumber, 2, 1, 1, 1)
        self.PointsNumberlineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.PointsNumberlineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.PointsNumberlineEdit.setObjectName("PointsNumberlineEdit")
        self.gridLayout.addWidget(self.PointsNumberlineEdit, 2, 2, 1, 1)
        self.labelTimeFrom = QtWidgets.QLabel(self.frame_2)
        self.labelTimeFrom.setObjectName("labelTimeFrom")
        self.gridLayout.addWidget(self.labelTimeFrom, 3, 0, 1, 1)
        self.horizontalSliderTimeFrom = QtWidgets.QSlider(self.frame_2)
        self.horizontalSliderTimeFrom.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderTimeFrom.setObjectName("horizontalSliderTimeFrom")
        self.gridLayout.addWidget(self.horizontalSliderTimeFrom, 3, 1, 1, 1)
        self.TimeFromlineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.TimeFromlineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TimeFromlineEdit.setObjectName("TimeFromlineEdit")
        self.gridLayout.addWidget(self.TimeFromlineEdit, 3, 2, 1, 1)
        self.labelTimeTo = QtWidgets.QLabel(self.frame_2)
        self.labelTimeTo.setObjectName("labelTimeTo")
        self.gridLayout.addWidget(self.labelTimeTo, 4, 0, 1, 1)
        self.horizontalSliderTimeTo = QtWidgets.QSlider(self.frame_2)
        self.horizontalSliderTimeTo.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderTimeTo.setObjectName("horizontalSliderTimeTo")
        self.gridLayout.addWidget(self.horizontalSliderTimeTo, 4, 1, 1, 1)
        self.TimeTolineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.TimeTolineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TimeTolineEdit.setObjectName("TimeTolineEdit")
        self.gridLayout.addWidget(self.TimeTolineEdit, 4, 2, 1, 1)
        self.labelAmplitude = QtWidgets.QLabel(self.frame_2)
        self.labelAmplitude.setObjectName("labelAmplitude")
        self.gridLayout.addWidget(self.labelAmplitude, 5, 0, 1, 1)
        self.horizontalSliderAmplitude = QtWidgets.QSlider(self.frame_2)
        self.horizontalSliderAmplitude.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderAmplitude.setObjectName("horizontalSliderAmplitude")
        self.gridLayout.addWidget(self.horizontalSliderAmplitude, 5, 1, 1, 1)
        self.AmplitudelineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.AmplitudelineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.AmplitudelineEdit.setObjectName("AmplitudelineEdit")
        self.gridLayout.addWidget(self.AmplitudelineEdit, 5, 2, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButtonStartSignalSending = QtWidgets.QPushButton(self.frame_4)
        self.pushButtonStartSignalSending.setMinimumSize(QtCore.QSize(60, 0))
        self.pushButtonStartSignalSending.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonStartSignalSending.setObjectName("pushButtonStartSignalSending")
        self.gridLayout_3.addWidget(self.pushButtonStartSignalSending, 0, 0, 1, 1)
        self.PauseSendingradioButton = QtWidgets.QRadioButton(self.frame_4)
        self.PauseSendingradioButton.setObjectName("PauseSendingradioButton")
        self.gridLayout_3.addWidget(self.PauseSendingradioButton, 1, 0, 1, 1)
        self.ResumeSendingradioButton = QtWidgets.QRadioButton(self.frame_4)
        self.ResumeSendingradioButton.setChecked(True)
        self.ResumeSendingradioButton.setAutoExclusive(True)
        self.ResumeSendingradioButton.setObjectName("ResumeSendingradioButton")
        self.gridLayout_3.addWidget(self.ResumeSendingradioButton, 1, 1, 1, 1)
        self.pushButtonStopSignalSending = QtWidgets.QPushButton(self.frame_4)
        self.pushButtonStopSignalSending.setMinimumSize(QtCore.QSize(60, 0))
        self.pushButtonStopSignalSending.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonStopSignalSending.setObjectName("pushButtonStopSignalSending")
        self.gridLayout_3.addWidget(self.pushButtonStopSignalSending, 2, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.EndlessSendingradioButton = QtWidgets.QRadioButton(self.frame_6)
        self.EndlessSendingradioButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.EndlessSendingradioButton.setObjectName("EndlessSendingradioButton")
        self.verticalLayout.addWidget(self.EndlessSendingradioButton)
        self.radioButton = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CyclesNumberspinBox = QtWidgets.QSpinBox(self.frame_6)
        self.CyclesNumberspinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.CyclesNumberspinBox.setMinimum(1)
        self.CyclesNumberspinBox.setMaximum(100)
        self.CyclesNumberspinBox.setObjectName("CyclesNumberspinBox")
        self.horizontalLayout_2.addWidget(self.CyclesNumberspinBox)
        self.label = QtWidgets.QLabel(self.frame_6)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_6.addWidget(self.frame_6, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame_4, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_5, 1, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(600, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ConfigFilenamelabel = QtWidgets.QLabel(self.frame_3)
        self.ConfigFilenamelabel.setLineWidth(4)
        self.ConfigFilenamelabel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ConfigFilenamelabel.setObjectName("ConfigFilenamelabel")
        self.horizontalLayout.addWidget(self.ConfigFilenamelabel)
        self.ConfigFileNamelineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.ConfigFileNamelineEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.ConfigFileNamelineEdit.setObjectName("ConfigFileNamelineEdit")
        self.horizontalLayout.addWidget(self.ConfigFileNamelineEdit)
        self.AutoFillpushButton = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AutoFillpushButton.sizePolicy().hasHeightForWidth())
        self.AutoFillpushButton.setSizePolicy(sizePolicy)
        self.AutoFillpushButton.setObjectName("AutoFillpushButton")
        self.horizontalLayout.addWidget(self.AutoFillpushButton)
        self.SavePresetpushButton = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SavePresetpushButton.sizePolicy().hasHeightForWidth())
        self.SavePresetpushButton.setSizePolicy(sizePolicy)
        self.SavePresetpushButton.setObjectName("SavePresetpushButton")
        self.horizontalLayout.addWidget(self.SavePresetpushButton)
        self.DeletePresetpushButton = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DeletePresetpushButton.sizePolicy().hasHeightForWidth())
        self.DeletePresetpushButton.setSizePolicy(sizePolicy)
        self.DeletePresetpushButton.setObjectName("DeletePresetpushButton")
        self.horizontalLayout.addWidget(self.DeletePresetpushButton)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.lcdNumber = QtWidgets.QLCDNumber(self.frame_8)
        self.lcdNumber.setMaximumSize(QtCore.QSize(150, 60))
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout_4.addWidget(self.lcdNumber)
        self.horizontalLayout_3.addWidget(self.frame_8)
        self.gridLayout_4.addWidget(self.frame_7, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelPhase.setText(_translate("MainWindow", "Phase:"))
        self.labelOmega.setText(_translate("MainWindow", "Omega:"))
        self.labelPointsNumber.setText(_translate("MainWindow", "Points Number:"))
        self.labelTimeFrom.setText(_translate("MainWindow", "Time From:"))
        self.labelTimeTo.setText(_translate("MainWindow", "Time To:"))
        self.labelAmplitude.setText(_translate("MainWindow", "Amplitude:"))
        self.pushButtonStartSignalSending.setText(_translate("MainWindow", "Start"))
        self.PauseSendingradioButton.setText(_translate("MainWindow", "Pause"))
        self.ResumeSendingradioButton.setText(_translate("MainWindow", "Resume"))
        self.pushButtonStopSignalSending.setText(_translate("MainWindow", "Stop"))
        self.EndlessSendingradioButton.setText(_translate("MainWindow", "Send Continuously"))
        self.radioButton.setText(_translate("MainWindow", "Send Cycles"))
        self.label.setText(_translate("MainWindow", "Cycles №"))
        self.ConfigFilenamelabel.setText(_translate("MainWindow", "Config Filename:"))
        self.AutoFillpushButton.setText(_translate("MainWindow", "Auto-Fill"))
        self.SavePresetpushButton.setText(_translate("MainWindow", "Save Preset"))
        self.DeletePresetpushButton.setText(_translate("MainWindow", "Delete Preset"))
        self.label_2.setText(_translate("MainWindow", "Current Cycle №:"))


from PlotCanvas import PlotCanvas