from PyQt5 import QtCore, QtWidgets, QtGui


class Ui_UserSignalWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(517, 820)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(230, 50, 271, 311))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.PointsNumberhorizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.PointsNumberhorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.PointsNumberhorizontalSlider.setObjectName("PointsNumberhorizontalSlider")
        self.gridLayout_10.addWidget(self.PointsNumberhorizontalSlider, 7, 0, 1, 1)
        self.VerticalOffsethorizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.VerticalOffsethorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.VerticalOffsethorizontalSlider.setObjectName("VerticalOffsethorizontalSlider")
        self.gridLayout_10.addWidget(self.VerticalOffsethorizontalSlider, 6, 0, 1, 1)
        self.AccelerationTimehorizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.AccelerationTimehorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.AccelerationTimehorizontalSlider.setObjectName("AccelerationTimehorizontalSlider")
        self.gridLayout_10.addWidget(self.AccelerationTimehorizontalSlider, 1, 0, 1, 1)
        self.StartTimehorizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.StartTimehorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.StartTimehorizontalSlider.setObjectName("StartTimehorizontalSlider")
        self.gridLayout_10.addWidget(self.StartTimehorizontalSlider, 0, 0, 1, 1)
        self.HighLevelFrequencyhorizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.HighLevelFrequencyhorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.HighLevelFrequencyhorizontalSlider.setObjectName("HighLevelFrequencyhorizontalSlider")
        self.gridLayout_10.addWidget(self.HighLevelFrequencyhorizontalSlider, 5, 0, 1, 1)
        self.PlateauTimehorizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.PlateauTimehorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.PlateauTimehorizontalSlider.setObjectName("PlateauTimehorizontalSlider")
        self.gridLayout_10.addWidget(self.PlateauTimehorizontalSlider, 2, 0, 1, 1)
        self.DecelerationTimehorizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.DecelerationTimehorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.DecelerationTimehorizontalSlider.setObjectName("DecelerationTimehorizontalSlider")
        self.gridLayout_10.addWidget(self.DecelerationTimehorizontalSlider, 3, 0, 1, 1)
        self.LowLevelFrequencyhorizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.LowLevelFrequencyhorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.LowLevelFrequencyhorizontalSlider.setObjectName("LowLevelFrequencyhorizontalSlider")
        self.gridLayout_10.addWidget(self.LowLevelFrequencyhorizontalSlider, 4, 0, 1, 1)
        self.EndTimehorizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.EndTimehorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.EndTimehorizontalSlider.setObjectName("EndTimehorizontalSlider")
        self.gridLayout_10.addWidget(self.EndTimehorizontalSlider, 8, 0, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(150, 50, 65, 311))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.StartTimelineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.StartTimelineEdit.setObjectName("StartTimelineEdit")
        self.verticalLayout.addWidget(self.StartTimelineEdit)
        self.AccelerationTimelineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.AccelerationTimelineEdit.setObjectName("AccelerationTimelineEdit")
        self.verticalLayout.addWidget(self.AccelerationTimelineEdit)
        self.PlateauTimelineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.PlateauTimelineEdit.setObjectName("PlateauTimelineEdit")
        self.verticalLayout.addWidget(self.PlateauTimelineEdit)
        self.DecelerationTimelineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.DecelerationTimelineEdit.setObjectName("DecelerationTimelineEdit")
        self.verticalLayout.addWidget(self.DecelerationTimelineEdit)
        self.LowLevelFrequencylineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.LowLevelFrequencylineEdit.setObjectName("LowLevelFrequencylineEdit")
        self.verticalLayout.addWidget(self.LowLevelFrequencylineEdit)
        self.HighLevelFrequencylineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.HighLevelFrequencylineEdit.setObjectName("HighLevelFrequencylineEdit")
        self.verticalLayout.addWidget(self.HighLevelFrequencylineEdit)
        self.VerticalOffsetlineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.VerticalOffsetlineEdit.setObjectName("VerticalOffsetlineEdit")
        self.verticalLayout.addWidget(self.VerticalOffsetlineEdit)
        self.PointsNumberlineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.PointsNumberlineEdit.setObjectName("PointsNumberlineEdit")
        self.verticalLayout.addWidget(self.PointsNumberlineEdit)
        self.EndTimelineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.EndTimelineEdit.setObjectName("EndTimelineEdit")
        self.verticalLayout.addWidget(self.EndTimelineEdit)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 51, 131, 301))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelStartTime = QtWidgets.QLabel(self.layoutWidget2)
        self.labelStartTime.setObjectName("labelStartTime")
        self.verticalLayout_2.addWidget(self.labelStartTime)
        self.labelAccelerationTime = QtWidgets.QLabel(self.layoutWidget2)
        self.labelAccelerationTime.setObjectName("labelAccelerationTime")
        self.verticalLayout_2.addWidget(self.labelAccelerationTime)
        self.labelPlateauTime = QtWidgets.QLabel(self.layoutWidget2)
        self.labelPlateauTime.setObjectName("labelPlateauTime")
        self.verticalLayout_2.addWidget(self.labelPlateauTime)
        self.labelDecelerationTime = QtWidgets.QLabel(self.layoutWidget2)
        self.labelDecelerationTime.setObjectName("labelDecelerationTime")
        self.verticalLayout_2.addWidget(self.labelDecelerationTime)
        self.labeLowLevelFrequency = QtWidgets.QLabel(self.layoutWidget2)
        self.labeLowLevelFrequency.setObjectName("labeLowLevelFrequency")
        self.verticalLayout_2.addWidget(self.labeLowLevelFrequency)
        self.labelHighLevelFrequency = QtWidgets.QLabel(self.layoutWidget2)
        self.labelHighLevelFrequency.setObjectName("labelHighLevelFrequency")
        self.verticalLayout_2.addWidget(self.labelHighLevelFrequency)
        self.labelVerticalOffset = QtWidgets.QLabel(self.layoutWidget2)
        self.labelVerticalOffset.setObjectName("labelVerticalOffset")
        self.verticalLayout_2.addWidget(self.labelVerticalOffset)
        self.labelPointsDensity = QtWidgets.QLabel(self.layoutWidget2)
        self.labelPointsDensity.setObjectName("labelPointsDensity")
        self.verticalLayout_2.addWidget(self.labelPointsDensity)
        self.labelEndTime = QtWidgets.QLabel(self.layoutWidget2)
        self.labelEndTime.setObjectName("labelEndTime")
        self.verticalLayout_2.addWidget(self.labelEndTime)
        self.ConfigFileNamelineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.ConfigFileNamelineEdit.setGeometry(QtCore.QRect(150, 20, 221, 22))
        self.ConfigFileNamelineEdit.setObjectName("ConfigFileNamelineEdit")
        self.ConfigFilenamelabel = QtWidgets.QLabel(self.centralwidget)
        self.ConfigFilenamelabel.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.ConfigFilenamelabel.setLineWidth(4)
        self.ConfigFilenamelabel.setObjectName("ConfigFilenamelabel")
        self.AutoFillpushButton = QtWidgets.QPushButton(self.centralwidget)
        self.AutoFillpushButton.setGeometry(QtCore.QRect(380, 20, 93, 28))
        self.AutoFillpushButton.setObjectName("AutoFillpushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 517, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelStartTime.setText(_translate("MainWindow", "Start Time:"))
        self.labelAccelerationTime.setText(_translate("MainWindow", "Acceleration Time:"))
        self.labelPlateauTime.setText(_translate("MainWindow", "Plateau Time:"))
        self.labelDecelerationTime.setText(_translate("MainWindow", "Deceleration Time:"))
        self.labeLowLevelFrequency.setText(_translate("MainWindow", "Low-level Frequency:"))
        self.labelHighLevelFrequency.setText(_translate("MainWindow", "High-level Frequency:"))
        self.labelVerticalOffset.setText(_translate("MainWindow", "Vertical Offset:"))
        self.labelPointsDensity.setText(_translate("MainWindow", "Points Number"))
        self.labelEndTime.setText(_translate("MainWindow", "End Time:"))
        self.ConfigFilenamelabel.setText(_translate("MainWindow", "Config Filename:"))
        self.AutoFillpushButton.setText(_translate("MainWindow", "Auto-Fill"))