from PyQt5 import QtCore, QtWidgets


class Ui_UserSignalWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEditSliderTimeToMax = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSliderTimeToMax.setGeometry(QtCore.QRect(680, 210, 31, 31))
        self.lineEditSliderTimeToMax.setObjectName("lineEditSliderTimeToMax")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(450, 170, 221, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalSliderTimeFrom = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSliderTimeFrom.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderTimeFrom.setObjectName("horizontalSliderTimeFrom")
        self.verticalLayout_3.addWidget(self.horizontalSliderTimeFrom)
        self.horizontalSliderTimeTo = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSliderTimeTo.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderTimeTo.setObjectName("horizontalSliderTimeTo")
        self.verticalLayout_3.addWidget(self.horizontalSliderTimeTo)
        self.horizontalSliderAmplitude = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSliderAmplitude.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderAmplitude.setObjectName("horizontalSliderAmplitude")
        self.verticalLayout_3.addWidget(self.horizontalSliderAmplitude)
        self.lineEditSliderTimeFromMax = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSliderTimeFromMax.setGeometry(QtCore.QRect(680, 170, 31, 31))
        self.lineEditSliderTimeFromMax.setObjectName("lineEditSliderTimeFromMax")
        self.lineEditSliderTimeToMin = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSliderTimeToMin.setGeometry(QtCore.QRect(410, 210, 31, 31))
        self.lineEditSliderTimeToMin.setObjectName("lineEditSliderTimeToMin")
        self.lineEditSliderAmplitudeMax = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSliderAmplitudeMax.setGeometry(QtCore.QRect(680, 250, 31, 31))
        self.lineEditSliderAmplitudeMax.setObjectName("lineEditSliderAmplitudeMax")
        self.lineEditSliderAmplitudeMin = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSliderAmplitudeMin.setGeometry(QtCore.QRect(410, 250, 31, 31))
        self.lineEditSliderAmplitudeMin.setObjectName("lineEditSliderAmplitudeMin")
        self.lineEditSliderTimeFromMin = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSliderTimeFromMin.setGeometry(QtCore.QRect(410, 170, 31, 31))
        self.lineEditSliderTimeFromMin.setObjectName("lineEditSliderTimeFromMin")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(110, 70, 282, 286))
        self.widget.setObjectName("widget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.labelStartTime = QtWidgets.QLabel(self.widget)
        self.labelStartTime.setObjectName("labelStartTime")
        self.gridLayout_7.addWidget(self.labelStartTime, 0, 0, 1, 1)
        self.lineEditStartTime = QtWidgets.QLineEdit(self.widget)
        self.lineEditStartTime.setObjectName("lineEditStartTime")
        self.gridLayout_7.addWidget(self.lineEditStartTime, 0, 1, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelAccelerationTime = QtWidgets.QLabel(self.widget)
        self.labelAccelerationTime.setObjectName("labelAccelerationTime")
        self.gridLayout_2.addWidget(self.labelAccelerationTime, 0, 0, 1, 1)
        self.lineEditAccelerationTime = QtWidgets.QLineEdit(self.widget)
        self.lineEditAccelerationTime.setObjectName("lineEditAccelerationTime")
        self.gridLayout_2.addWidget(self.lineEditAccelerationTime, 0, 1, 1, 1)
        self.labelPlateauTime = QtWidgets.QLabel(self.widget)
        self.labelPlateauTime.setObjectName("labelPlateauTime")
        self.gridLayout_2.addWidget(self.labelPlateauTime, 1, 0, 1, 1)
        self.lineEditPlateauTime = QtWidgets.QLineEdit(self.widget)
        self.lineEditPlateauTime.setObjectName("lineEditPlateauTime")
        self.gridLayout_2.addWidget(self.lineEditPlateauTime, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelDecelerationTime = QtWidgets.QLabel(self.widget)
        self.labelDecelerationTime.setObjectName("labelDecelerationTime")
        self.gridLayout.addWidget(self.labelDecelerationTime, 0, 0, 1, 1)
        self.lineEditDecelerationTime = QtWidgets.QLineEdit(self.widget)
        self.lineEditDecelerationTime.setObjectName("lineEditDecelerationTime")
        self.gridLayout.addWidget(self.lineEditDecelerationTime, 0, 1, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.labeLowLevelFrequency = QtWidgets.QLabel(self.widget)
        self.labeLowLevelFrequency.setObjectName("labeLowLevelFrequency")
        self.gridLayout_5.addWidget(self.labeLowLevelFrequency, 0, 0, 1, 1)
        self.labelHighLevelFrequency = QtWidgets.QLabel(self.widget)
        self.labelHighLevelFrequency.setObjectName("labelHighLevelFrequency")
        self.gridLayout_5.addWidget(self.labelHighLevelFrequency, 1, 0, 1, 1)
        self.labelVerticalOffset = QtWidgets.QLabel(self.widget)
        self.labelVerticalOffset.setObjectName("labelVerticalOffset")
        self.gridLayout_5.addWidget(self.labelVerticalOffset, 2, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEditLowLevelFrequency = QtWidgets.QLineEdit(self.widget)
        self.lineEditLowLevelFrequency.setObjectName("lineEditLowLevelFrequency")
        self.verticalLayout.addWidget(self.lineEditLowLevelFrequency)
        self.lineEditHighLevelFrequency = QtWidgets.QLineEdit(self.widget)
        self.lineEditHighLevelFrequency.setObjectName("lineEditHighLevelFrequency")
        self.verticalLayout.addWidget(self.lineEditHighLevelFrequency)
        self.lineEditVerticalOffset = QtWidgets.QLineEdit(self.widget)
        self.lineEditVerticalOffset.setObjectName("lineEditVerticalOffset")
        self.verticalLayout.addWidget(self.lineEditVerticalOffset)
        self.gridLayout.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 2)
        self.labelPointsNumber = QtWidgets.QLabel(self.widget)
        self.labelPointsNumber.setObjectName("labelPointsNumber")
        self.gridLayout_4.addWidget(self.labelPointsNumber, 1, 0, 1, 1)
        self.lineEditPointsNumber = QtWidgets.QLineEdit(self.widget)
        self.lineEditPointsNumber.setObjectName("lineEditPointsNumber")
        self.gridLayout_4.addWidget(self.lineEditPointsNumber, 1, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 0, 0, 1, 2)
        self.labelEndTime = QtWidgets.QLabel(self.widget)
        self.labelEndTime.setObjectName("labelEndTime")
        self.gridLayout_6.addWidget(self.labelEndTime, 1, 0, 1, 1)
        self.lineEditEndTime = QtWidgets.QLineEdit(self.widget)
        self.lineEditEndTime.setObjectName("lineEditEndTime")
        self.gridLayout_6.addWidget(self.lineEditEndTime, 1, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEditSliderTimeFromMax.setText(_translate("MainWindow", "600"))
        self.lineEditSliderAmplitudeMax.setText(_translate("MainWindow", "10.0"))
        self.lineEditSliderAmplitudeMin.setText(_translate("MainWindow", "0.0"))
        self.lineEditSliderTimeFromMin.setText(_translate("MainWindow", "0.0"))
        self.labelStartTime.setText(_translate("MainWindow", "Start Time:"))
        self.labelAccelerationTime.setText(_translate("MainWindow", "Acceleration Time:"))
        self.labelPlateauTime.setText(_translate("MainWindow", "Plateau Time:"))
        self.labelDecelerationTime.setText(_translate("MainWindow", "Deceleration Time:"))
        self.labeLowLevelFrequency.setText(_translate("MainWindow", "Low-level Frequency:"))
        self.labelHighLevelFrequency.setText(_translate("MainWindow", "High-level Frequency:"))
        self.labelVerticalOffset.setText(_translate("MainWindow", "Vertical Offset:"))
        self.labelPointsNumber.setText(_translate("MainWindow", "Points Number"))
        self.labelEndTime.setText(_translate("MainWindow", "End Time:"))